# .devcontainer/Dockerfile

FROM mcr.microsoft.com/devcontainers/javascript-node:20

# Install Expo CLI globally
RUN npm install -g expo-cli

# Install Firebase CLI globally
RUN npm install -g firebase-tools
